export const brand = {
  name: 'چشمک',
  nameEn: 'Cheshmak',
  logo: '/assets/img/logo.png',
  tagline: 'فروشگاه آنلاین عینک',
  description: 'خرید عینک طبی، آفتابی و فریم‌های روز از فروشگاه چشمک.',
  keywords: [
    'عینک',
    'عینک طبی',
    'عینک آفتابی',
    'فریم عینک',
    'لنز',
    'فروشگاه عینک',
    'چشمک',
  ],
  email: '--',
  supportEmail: '--',
  promoCode: 'CHESHMAK2026',
  phone: '۰۹۰۳۴۸۸۳۲۳۸',
  phoneTel: '+989034883238',
  address: 'زنجان، خرمدره، مجتمع بهاران، همکف، واحد ۵ (برسام بوتیک)',
  location: {
    lat: 36.206015,
    lng: 49.191954,
  },
  social: {
    instagram: 'https://www.instagram.com/barsam.boutique1',
    telegram: 'https://t.me/barsam16',
    whatsapp: 'https://api.whatsapp.com/message/DV2NE22YBAD4N1',
  },
} as const;
